//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD_APPLICATION.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employeetbl
    {
        public int EID { get; set; }
        public string ENAME { get; set; }
        public string ELOCATION { get; set; }
        public Nullable<int> ESALARY { get; set; }
    }
}
